### PR TITLE
contributing italian translation

### PR DESCRIPTION
**Pull request by therealpecus**
this is the italian translation of the 17 panels (I left the 18th in English) + one page

### CODE REVIEW

**Comment by lbrutti** [comment]
seems like all of us Italian missed the @robypez translation published here: https://www.dday.it/redazione/34936/le-app-di-tracciamento-spiegate-con-un-fumetto-perche-servono-e-perche-sono-sicure

AFAIK he should have sent a pull request here...

**Comment by scriptamanent** [comment]
I send the email with all the panels to "m.veale@ucl.ac.uk" a couple of days ago...

**Comment by robypez** [comment]
Sorry wrong account...
I follow the istructions, 

"Please translate (fonts are Patrick Hand and Open Sans) and if you send the files or notify m.veale@ucl.ac.uk, we will upload them to the repo for others to use. If possible, we would appreciate you also licensing your translations CC-0"

I send everything on monday to that email...

**Comment by therealpecus** [comment]
@robypez dday has published the comic with full copyright (© riproduzione riservata). you should ask them to amend the article so that the comic reflects its public domain status

**Comment by therealpecus** [comment]
BTW, I hadn't seen it and I find it a better translation overall!

**Comment by robypez** [comment]
I'm the author, (© riproduzione riservata) is encoded on the page and I cannot remove it. But when I send the email I specify that we will provide the content CC-0

**Comment by veale** [comment]
Hi, apologies we have dropped the ball on translations and putting them up from email in this very hectic period. If they are CC-0 we are happy to put both of them up as we have for the Dutch version.

**Pull request merged**
